_main_app/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("model_app/", include("model_app.urls")),
    path("", include("ui_app.urls")),
    path("", include("media_server_app.urls")),
]

media_server_app/urls.py
from django.urls import path
from .views import media_server

urlpatterns = [path("media/<path:path>", media_server)]

model_app/urls.py
from django.urls import path
from .views import model_app, calibrate

app_name = 'model_app'
urlpatterns = [path('', model_app, name='model'), path(
    'calibrate', calibrate, name='calibrate')]

ui_app/urls.py
from django.urls import path
from .views import ui_app, calibrate, score

urlpatterns = [path('', ui_app), path(
    'calibrate', calibrate), path('score', score)]

media_server_app/models.py
from django.db import models

# Create your models here.

ui_app/models.py
from django.db import models

# Create your models here.


class Score(models.Model):
    bri = models.FloatField()
    datetime = models.DateTimeField(auto_now_add=True)

    height = models.FloatField()
    waist = models.FloatField()

media_server_app/views.py
from django.shortcuts import redirect
from django.http import FileResponse, Http404
from django.conf import settings
import os


def media_server(request, path):

    file_path = os.path.join(settings.MEDIA_ROOT, path)

    if ".." in file_path:
        return redirect("https://giphy.com/gifs/Tgn493H3TI544")

    if not os.path.exists(file_path):
        raise Http404("Non existing file")

    return FileResponse(open(file_path, "rb"))

model_app/views.py
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.core.files.storage import FileSystemStorage
from datetime import datetime

from django.shortcuts import render
from model_app.ai.ai import model, calc_bri


def get_bri_json(request):
    widths, heights = [], []

    titles = ['Original 1', 'Original 2', 'Mask 1',
              'Mask 2', 'Ellipse 1', 'Ellipse 2']

    imgs = []
    masks = []
    curves = []

    # Get the files from the request
    fs = FileSystemStorage()
    files = request.FILES

    # Save each file
    for index, file in enumerate(files.values()):

        # Generate filename with current datetime
        current_datetime = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = fs.save(f"{current_datetime}_{index}.jpg", file)

        imgs.append(fs.url(filename))
        masks.append(fs.url(filename.split('.')[0] + '_mask.png'))
        curves.append(fs.url(filename.split('.')[0] + '_lines.png'))

        ########################################
        # MAKE THE PREDICTIONS
        model.set_body(fs.path(filename))
        #
        heights.append(model.get_body_height())
        widths.append(model.get_body_width(level=0.45))
        #
        model.draw_markers(level=0.45)

    rslt_urls = imgs + masks + curves
    rslt_urls = {titles[_]: rslt_urls[_] for _ in range(len(rslt_urls))}

    p, h, bri = calc_bri(widths, heights)

    return JsonResponse({'urls': rslt_urls,
                         'bri': round(bri, 1),
                         #
                         'p': p, 'h': h
                         #
                         })


@csrf_exempt
@require_http_methods(["POST"])
def model_app(request):
    return get_bri_json(request)


@csrf_exempt
@require_http_methods(["POST"])
def calibrate(request):
    fs = FileSystemStorage()
    files = request.FILES

    # Save each file
    for index, file in enumerate(files.values()):

        # Generate filename with current datetime
        current_datetime = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = fs.save(f"{current_datetime}_{index}.jpg", file)

        # calibrate
        model.calibrate(fs.path(filename), 179)

        with open('calibration.txt', 'w') as f:
            f.write(f"{model.resize_factor}")

    return JsonResponse({})

ui_app/views.py
from django.shortcuts import render
from ui_app.models import Score


def ui_app(request):
    return render(request, 'ui_app/ui_app.html', {})


def calibrate(request):
    return render(request, 'ui_app/calibrate.html', {})


def score(request):
    data = Score.objects.all()
    data = list(data)
    data.reverse()

    return render(request, 'ui_app/score.html', {
        'scores': data
    })

templates/model_app/model_app.html
model_app

templates/ui_app/calibrate.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Calibration</title>

    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}">

    <link rel="stylesheet" href="{% static 'widgets/theme_dark.css' %}">
    <link rel="stylesheet" href="{% static 'widgets/global/button/button.css' %}">

    <link rel="stylesheet" href="{% static 'ui_app/ui_app.css' %}">



</head>

<body>
    {% include 'widgets/app/calibration/calibration.html' %}    
</body>

</html>

templates/ui_app/score.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Score</title>

    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}">

    <link rel="stylesheet" href="{% static 'widgets/theme_dark.css' %}">
    <link rel="stylesheet" href="{% static 'widgets/global/section/section.css' %}">
    <link rel="stylesheet" href="{% static 'widgets/global/table/table.css' %}">

    <link rel="stylesheet" href="{% static 'ui_app/score.css' %}">
</head>

<body>

    <div class="section">
        <div class="section_title">
            <h1>Scores Table</h1>
        </div>
        <div class="section_content">
            <table>
                <thead>
                    <th>Height (cm)</th>
                    <th>Waist (cm)</th>
                    <th>BRI</th>
                </thead>
                <tbody>
                    {% for i in scores%}
                    <tr>
                        <td>{{i.height|floatformat:2}} cm</td>
                        <td>{{i.waist|floatformat:2}} cm</td>

                        {% if i.bri > 6.9 %}
                        <td class="red">{{i.bri|floatformat:2}}</td>
                        {% else %}
                        <td class="green">{{i.bri|floatformat:2}}</td>
                        {% endif %}

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</body>

</html>

templates/ui_app/ui_app.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>HI_AI</title>

    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'assets/images/favicon.png' %}">

    <link rel="stylesheet" href="{% static 'widgets/theme_dark.css' %}">
    <link rel="stylesheet" href="{% static 'widgets/global/button/button.css' %}">

    <link rel="stylesheet" href="{% static 'ui_app/ui_app.css' %}">



</head>

<body>
    {% include 'widgets/app/capture/capture.html' %}

    {% include 'widgets/app/result_popup/result_popup.html' %}
</body>

</html>

templates/widgets/app/calibration/calibration.html
{% load static %}
<link rel="stylesheet" href="{% static 'widgets/app/calibration/calibration.css' %}">


<div id="capture">

    <!-- CAMERA -->
    <div id="webcam">
        {% include 'widgets/global/webcam/webcam.html' %}
    </div>

    <!-- BUTTON -->
    <script src="{% static 'widgets/app/capture/upload.js' %}"></script>
    <button id="next">Calibrate</button>



    <script>
        // INIT THE CAMERA 
        const cam = new WebCam('webcam');

        // NEXT LOGIC
        var images = [];

        const next_btn = document.getElementById('next')
        next_btn.addEventListener('click', function () {
            if (cam.preview) {
                if (images.length < 1) {
                    images.push(cam.data);
                    cam.toggle_preview()
                    //                  
                    next_btn.innerHTML = `Next (${images.length}/2)`
                }
                if (images.length == 1) {
                    next_btn.innerHTML = `Processing...`
                    uploadImages(images, "{% url 'model_app:calibrate' %}", function (_) {

                        document.location.href = '/'
                    });
                }
            }
        })


        // KB
        document.addEventListener('keypress', function (e) {
            if (event.key === "Enter")
                cam.btn.click()
            if (event.key === " ")
                next_btn.click()
        })
    </script>
</div>

templates/widgets/app/capture/capture.html
{% load static %}
<link rel="stylesheet" href="{% static 'widgets/app/capture/capture.css' %}">


<div id="capture">

    <!-- CAMERA -->
    <div id="webcam">
        {% include 'widgets/global/webcam/webcam.html' %}
    </div>

    <!-- BUTTON -->
    <script src="{% static 'widgets/app/capture/upload.js' %}"></script>
    <button id="next">Next (0/2)</button>



    <script>
        // INIT THE CAMERA 
        const cam = new WebCam('webcam');

        // NEXT LOGIC
        var images = [];

        const next_btn = document.getElementById('next')
        next_btn.addEventListener('click', function () {
            if (cam.preview) {
                if (images.length < 2) {
                    images.push(cam.data);
                    cam.toggle_preview()
                    //                  
                    next_btn.innerHTML = `Next (${images.length}/2)`
                }
                if (images.length == 2) {
                    next_btn.innerHTML = `Processing...`
                    uploadImages(images, "{% url 'model_app:model' %}", function (_) {
                        //recieve the result 
                        const rslt = new Map(Object.entries(_))

                        // RENDER THE IMAGES                                                
                        render_images(new Map(Object.entries(rslt.get('urls'))));
                        set_bri(rslt.get('bri'))

                        //toggle the result panel
                        toggle_result();

                    });
                }
            }
        })

        // KB
        document.addEventListener('keypress', function (e) {
            if (event.key === "Enter")
                cam.btn.click()
            if (event.key === " ")
                next_btn.click()
        })


    </script>
</div>

templates/widgets/app/loading_screen/loading_screen.html
{% load static %}

<link rel="stylesheet" href="{% static 'widgets/app/loading_screen/loading_screen.css' %}">
<div id="loading_screen">

   <!-- <img src="{% static 'assets/images/logo_long.png' %}">
--><div class="loader">
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
    </div>

    <script src="{% static 'widgets/app/loading_screen/loading_screen.js' %}"></script>
    

</div>

templates/widgets/app/result_popup/result_popup.html
{% load static %}
<link rel="stylesheet" href="{% static 'widgets/global/section/section.css' %}">
<link rel="stylesheet" href="{% static 'widgets/app/result_popup/result_popup.css' %}">


<div id="result_popup" class="hide">
    <div class="section">
        <div class="section_content">
            <!--  -->
            <div class="section" id="indice">
                <div class="section_content">
                    <div class="indice_circle" id="indice_circle">
                        <h1>BRI</h1>
                        <h1 id="indice_val">999</h1>
                        <h2 id="risk_label" >low risk</h2>
                    </div>
                </div>
            </div>
            <!--  -->
            <div class="section" id="results">
                <div class="section_title">
                    <h1>Results Visualization</h1>
                </div>
                <div class="section_content grid2" id="imgs_grid">
                </div>
            </div>
        </div>

    </div>


    <script src="{% static 'widgets/app/result_popup/result_popup.js' %}"></script>

</div>

templates/widgets/global/form/form.html
{% load static %}
<link rel="stylesheet" href="{% static 'widgets/form/form.css' %}">


<div class="section input_section" id="{{field.label}}">
    <div class="section_title input_tag">
        {{ field.label }}
    </div>
    <div class="section_content">
        {{ field }}        

        {% for error in field.errors %}
        <div class="input_error">
            {{ error }}
        </div>
        {% endfor %}

    </div>


</div>

templates/widgets/global/webcam/webcam.html
{% load static %}
<link rel="stylesheet" href="{% static 'widgets/global/webcam/webcam.css' %}">

<div class="webcam">
    <video autoplay></video>
    <canvas></canvas>
    <button>
        <img src="{% static 'widgets/global/webcam/shutter.png' %}" alt="">
    </button>
    <script src="{% static 'widgets/global/webcam/webcam.js' %}"></script>
</div>